version: '3.8'

services:
  jabka-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jabka-bot
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "bot.py"]
    restart: unless-stopped
